const projects=[
 {name:'MetalCompositor',type:'REAL-TIME GRAPHICS',desc:'Multi-pass Metal compositor with linear-light and tile-memory programmable blending, P3 color management, and a frame scheduler that tracks GPU time against display refresh.',tags:'SWIFT 6 · METAL · MSL · MACOS',src:'https://github.com/devthedevil/metal-compositor'},
 {name:'Pitch Perfect',type:'IOS AUDIO',desc:'iOS voice app chaining AVAudioEngine nodes for six real-time effects including time-pitch, echo, and reverb.',tags:'SWIFT · UIKIT · AVFOUNDATION',src:'https://github.com/devthedevil/Pitch_Perfect'},
 {name:'TradeSentinel',type:'LIVE PRODUCT',desc:'Market-focused application with a public demo and source repository.',tags:'REAL-TIME · WEB APP',src:'https://github.com/devthedevil/tradesentinel',demo:'https://tradesentinel.vercel.app/'},
 {name:'AskMyStore',type:'AI ORCHESTRATION',desc:'Store assistant built with LangGraph orchestration and a live demo.',tags:'LANGGRAPH · LLM',src:'https://github.com/devthedevil/AskMyStore',demo:'https://ask-my-store.vercel.app/'},
 {name:'Strangers',type:'WEB EXPERIENCE',desc:'Interactive web application with a live demo.',tags:'REACT · WEB APP',src:'https://github.com/devthedevil/Strangers',demo:'https://strangers-react.vercel.app/'},
 {name:'Oxide-HV',type:'VIRTUALIZATION',desc:'Rust hypervisor project with a live project experience.',tags:'RUST · HYPERVISOR',src:'https://github.com/devthedevil/oxide-hv',demo:'https://oxide-hv.vercel.app/'},
 {name:'EXPOS — Experimental Operating System',type:'SYSTEMS',desc:'An experimental operating system project exploring low-level software foundations.',tags:'C · OPERATING SYSTEMS',src:'https://github.com/devthedevil/EXPOS'},
 {name:'Character Device Driver',type:'KERNEL',desc:'Linux character device driver exploring kernel interfaces and device I/O.',tags:'C · LINUX KERNEL',src:'https://github.com/devthedevil/Character-Device-Driver'},
 {name:'LangChain Chat with Search',type:'AI APPLICATION',desc:'Conversational search application built with LangChain.',tags:'LANGCHAIN · SEARCH · LLM',src:'https://github.com/devthedevil/LangChain-Chat-with-Search'},
 {name:'16-Bit RISC Processor',type:'COMPUTER ARCHITECTURE',desc:'A 16-bit RISC processor implementation from a hardware lab project.',tags:'PROCESSOR · HARDWARE',src:'https://github.com/devthedevil/Hardware-lab'},
 {name:'Real-time Stock Market Analysis Pipeline',type:'DATA PIPELINE',desc:'Streaming pipeline for real-time market analysis.',tags:'STREAMING · ANALYTICS',src:'https://github.com/devthedevil/Realtime-Stock-Market-Analysis'},
 {name:'CME MDP 3.0 Multicast Feed Handler',type:'LOW-LATENCY SYSTEMS',desc:'C++ multicast market-data feed handler.',tags:'C++ · MULTICAST · MARKET DATA',src:'https://github.com/devthedevil/CME-Multicast-Market-Data-Feed-Handler-C-'},
 {name:'Keystone',type:'DISTRIBUTED SYSTEMS',desc:'Transactional key-value store for Kubernetes control-plane metadata with MVCC, Raft replication, and etcd-style watches.',tags:'GO · RAFT · GRPC',src:'https://github.com/devthedevil/keystone'},
 {name:'Voting App',type:'KUBERNETES',desc:'Multi-tenant Kubernetes deployment with namespace isolation, self-healing pods, autoscaling, and Prometheus alerting.',tags:'KUBERNETES · HELM · GO',src:'https://github.com/devthedevil/Kubernetes-K8'},
 {name:'Strata',type:'STORAGE',desc:'C++ storage server project.',tags:'C++ · STORAGE SERVER',src:'https://github.com/devthedevil/strata'},
 {name:'AgentFlow',type:'AGENT SYSTEMS',desc:'Agent orchestration project built with the OpenAI Agent SDK.',tags:'AGENTS · ORCHESTRATION',src:'https://github.com/devthedevil/openAI-Agent-SDK'},
 {name:'AgentEval',type:'AI QUALITY',desc:'Evaluation tooling for Swift agent workflows.',tags:'SWIFT · EVALUATION',src:'https://github.com/devthedevil/swift-agent-evals'},
 {name:'MCP',type:'DEVELOPER TOOLING',desc:'Model Context Protocol project exploring connected tools and context.',tags:'MCP · INTEGRATION',src:'https://github.com/devthedevil/MCP'},
 {name:'AeroInvoice',type:'AI AUTOMATION',desc:'AI-powered invoice ingestion and quote extraction API.',tags:'AI · DOCUMENT PROCESSING · API',src:'https://github.com/devthedevil/aero-invoice-intelligence'},
 {name:'adserve',type:'BACKEND SYSTEMS',desc:'An ad-serving system project.',tags:'BACKEND · SYSTEMS',src:'https://github.com/devthedevil/adserve'},
 {name:'Hire Loop',type:'PRODUCT ENGINEERING',desc:'Hiring workflow application project.',tags:'WEB APP · PRODUCT ENGINEERING',src:'https://github.com/devthedevil/hireloop'},
 {name:'Tic Tac Toe',type:'ANDROID',desc:'Android implementation of the classic strategy game.',tags:'ANDROID · MOBILE',src:'https://github.com/devthedevil/TicTacToe-Game'}
];
const projectsGrid=document.querySelector('#projectsGrid');
projectsGrid.innerHTML=projects.map((p,i)=>`<article class="project-card"><div class="project-meta"><span>${p.type}</span><span>${String(i+1).padStart(2,'0')}</span></div><h3>${p.name}</h3><p>${p.desc}</p><div class="project-tags">${p.tags}</div><div class="project-links"><a href="${p.src}" target="_blank" rel="noreferrer">SourceCode <span>↗</span></a>${p.demo?`<a href="${p.demo}" target="_blank" rel="noreferrer">Technical Demo <span>↗</span></a>`:''}</div></article>`).join('');
const focusLines=['capture with intent','keep motion in sync','make every interaction accessible','protect the moment being shared'];let focusIndex=0;const focus=document.querySelector('#focusText');
setInterval(()=>{focus.classList.add('fade');setTimeout(()=>{focusIndex=(focusIndex+1)%focusLines.length;focus.textContent=focusLines[focusIndex];focus.classList.remove('fade')},230)},3000);
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target)}}),{threshold:.1});document.querySelectorAll('.job,.project-card,.craft-notes article,.publication').forEach(item=>{item.classList.add('reveal');observer.observe(item)});
